version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: eslint
    versions:
    - 7.27.0
  - dependency-name: ava
    versions:
    - 3.15.0
